default: &default
  host: localhost
  user: postgres
  adapter: postgres
  password: ""

development:
  <<: *default
  db: rickandmorty

test:
  <<: *default
  db: rickandmorty

production:
  <<: *default
  db: rickandmorty

