default: &default
  host: localhost
  user: postgres
  adapter: postgres
  password: ""

development:
  <<: *default
  db: milenio

test:
  <<: *default
  db: milenio

production:
  <<: *default
  db: milenio

